### PR TITLE
Make default printer an exec configured w/ a param

### PR DESCRIPTION
**Pull request by lamawithonel**
This removes the `default_printer` type and provider and makes it an
exec instead, fed by a parameter to the init class.  Using an exec like
this ensures the attribute remains singleton.

### CODE REVIEW

**Comment by lamawithonel** [comment]
Refs #41

**Comment by lamawithonel** [comment]
I've updated this with a few additional changes I needed for my environment.

- Fixed for null Hiera lookup of `cups::printers` hash (pretty much the same as #54)
- Added another Hiera lookup for the `printer_defaults` type
- Cleaned up for readability and consistency with community standards (from #56)

**Comment by mosen** [comment]
Thanks for the changes, will merge shortly.

**Comment by lamawithonel** [comment]
Thanks, and let me know if you need anything else, like rspec-puppet tests.

**Pull request merged**
